name: MoFlow

on:
  push:
    branches:
    - main

jobs:
   example-job:
      runs-on: ubuntu-latest
     
      steps:
          - name: say hello
            run: echo "welcome basha"

          - name: check repo
            uses: actions/checkout@v4.2.2

          - name: List repo files
            run: ls -la
